client-id: gatekeeper
client-secret: ZAEKi6DprpQPr5SwKnA2Ht6AUOP9YCLd # require for access_type: confidential
# Note the redirection-url is optional, it will default to the the URL scheme and host,
# only in case of forward auth it will use X-Forwarded-Proto / X-Forwarded-Host, please see forward-auth section
discovery-url: http://keycloak:8080/realms/master
# Indicates we should deny by default all requests and explicitly specify what is permitted, default true
enable-default-deny: true
encryption-key: AgXa7xRcoClDEU0ZDSH4X0XhL5Qy2Z2j
listen: :3000
upstream-url: http://web-app:7070
secure-cookie: false
# a collection of resource i.e. URLs that you wish to protect, this are simple gatekeeper authorization rules,
# to get more complex authorization you can look at external authorization section in our documentation
resources:
    - uri: /admin*
      methods:
          - GET
      roles:
          - gatekeeper:admin
      require-any-role: true
    - uri: /public/*
        # Allow access to the resource above
      white-listed: true
    - uri: /favicon
        # Allow access to the resource above
      white-listed: true
    - uri: /css/*
        # Allow access to the resource above
      white-listed: true
    - uri: /img/*
        # Allow access to the resource above
      white-listed: true
# Adds custom headers
headers:
    myheader1: value_1
    myheader2: value_2
