version: "3.5"
services:
    identity-manager:
        build:
            context: .
            dockerfile: identity-manager/Dockerfile
        image: identity-manager
        container_name: identity-manager
        networks:
            - eoepca_network
        ports:
            - '8080:8080'
    identity-api:
        build:
            context: .
            dockerfile: identity-api/Dockerfile
        image: identity-api
        container_name: identity-api
        networks:
            - eoepca_network
        ports:
            - '8080:8081'
        volumes:
            - ./identity-api/config:/app/config
    keycloak:
        image: quay.io/keycloak/keycloak
        container_name: keycloak
        networks:
            - eoepca_network
        ports:
            - '8080:8082'
    postgres:
        image: postgres
        container_name: postgres
        networks:
            - eoepca_network
        ports:
            - '5432:5432'
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
networks:
    eoepca_network:
        driver: bridge
        name: eoepcanetwork
