version: "3.5"
services:
    identity-manager:
        build: https://github.com/EOEPCA/um-identity-manager#develop
        container_name: identity-manager
        networks:
            - eoepca_network
        ports:
            - '4200:80'
        volumes:
            - ./identity-manager:/app
            - /app/node_modules
    identity-api:
        build: https://github.com/EOEPCA/um-identity-api#develop
        container_name: identity-api
        networks:
            - eoepca_network
        ports:
            - '8080:8081'
        volumes:
            - ./identity-api/config:/app/config
    keycloak:
        image: quay.io/keycloak/keycloak:21.0
        container_name: keycloak
        networks:
            - eoepca_network
        ports:
            - '8080:8080'
        environment:
            - KEYCLOAK_LOGLEVEL=DEBUG
            - WILDFLY_LOGLEVEL=DEBUG
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin_Abcd1234#
            - KC_PROXY=edge
            - KC_HOSTNAME_STRICT=false
            - KC_DB=postgres
            - KC_DB_URL_HOST=postgres
            - KC_DB_PASSWORD=123456
            - KC_DB_USERNAME=keycloak
            - KC_DB_URL_PORT=5432
        command: "start"
    postgres:
        image: postgres:12.10
        container_name: postgres
        networks:
            - eoepca_network
        ports:
            - '5432:5432'
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=keycloak
            - POSTGRES_USER=keycloak
            - POSTGRES_PASSWORD=123456
            - PGPASSWORD=123
            - PGDATA=/var/lib/postgresql/data/keycloak
    oauth2-proxy:
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
        container_name: oauth2-proxy
        networks:
            - eoepca_network
        ports:
            - '4180:4180'
        environment:
            - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
            - OAUTH2_PROXY_COOKIE_SECURE=true
            - OAUTH2_PROXY_COOKIE_SECRET=JxJZrvNo4z1VJIiDMDGJe3q4TjmpVxMNHziW97J9UAo=
            - OAUTH2_PROXY_UPSTREAMS=https://dummy-service.develop.eoepca.org
            - OAUTH2_PROXY_COOKIE_DOMAINS=.eoepca.org # Required so cookie can be read on all subdomains.
            - OAUTH2_PROXY_WHITELIST_DOMAINS=.eoepca.org # Required to allow redirection back to original requested target.
            - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
            # allow accounts to sign-in with empty emails
            # https://github.com/oauth2-proxy/oauth2-proxy/issues/769#issuecomment-808916298
            - OAUTH2_PROXY_EMAIL_DOMAINS=*
            - OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL=true
            - OAUTH2_PROXY_OIDC_EMAIL_CLAIM=sub
            # keycloak provider
            - OAUTH2_PROXY_CLIENT_ID=oauth2-proxy
            - OAUTH2_PROXY_CLIENT_SECRET=secret
            - OAUTH2_PROXY_REDIRECT_URL=https://identity-proxy.local.eoepca.org/oauth2/callback
            # in this case oauth2-proxy is going to visit
            # https://identity-keycloak.local.eoepca.org/realms/dummy-service/.well-known/openid-configuration for configuration
            - OAUTH2_PROXY_OIDC_ISSUER_URL=https://identity-keycloak.local.eoepca.org/realms/dummy-service
            - OAUTH2_PROXY_PROVIDER=oidc
            - OAUTH2_PROXY_PROVIDER_DISPLAY_NAME=Keycloak
networks:
    eoepca_network:
        driver: bridge
        name: eoepcanetwork
