apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.name" . }}-secret
  namespace: {{ template "keycloak.namespace" $ }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.secrets.keycloakAdminPassword }}"
  KC_DB_PASSWORD: "{{ .Values.secrets.kcDbPassword }}"