{{ if .Values.volumeClaim.create }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.name }}
  labels:
    type: {{ .Values.persistence.type }}
    eoepca_type: userman
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  capacity:
    storage: {{ .Values.persistence.storage }}
  accessModes:
    {{- with .Values.persistence.accessModes }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}
  hostPath:
    path: {{ .Values.persistence.hostPath.path }} # Sets PV's host path
{{ end }}