apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.name" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
  namespace: {{ template "nginx.namespace" $ }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
