identity-keycloak:
  enabled: true
  deployment:
    image:
      repository: quay.io/keycloak/keycloak
      pullPolicy: IfNotPresent
identity-postgres:
  enabled: true
  deployment:
    image:
      repository: postgres
      pullPolicy: IfNotPresent
identity-api:
  enabled: false
  deployment:
    image:
      repository: ghcr.io/eoepca/um-identity-api
      pullPolicy: Always
identity-manager:
  enabled: false
  deployment:
    image:
      repository: ghcr.io/eoepca/um-identity-manager
      pullPolicy: Always
identity-gatekeeper:
  enabled: true
  deployment:
    image:
      repository: quay.io/gogatekeeper/gatekeeper
      pullPolicy: IfNotPresent
identity-spring-boot-echo:
  enabled: false
  deployment:
    image:
      repository: ghcr.io/eoepca/um-spring-boot-echo
      pullPolicy: IfNotPresent
identity-oauth2-proxy:
  enabled: false
  deployment:
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      pullPolicy: IfNotPresent
identity-nginx:
  enabled: false
  deployment:
    image:
      repository: nginxinc/nginx-unprivileged
      pullPolicy: IfNotPresent