apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.name" . }}-config
  namespace: {{ template "keycloak.namespace" $ }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  KEYCLOAK_LOGLEVEL: "{{ .Values.configMap.keycloakLogLevel }}"
  WILDFLY_LOGLEVEL: "{{ .Values.configMap.wildflyLoglevel }}"
  KEYCLOAK_ADMIN: "{{ .Values.configMap.keycloakAdmin }}"
  KC_HOSTNAME_STRICT: "{{ .Values.configMap.kcHostnameStrict }}"
  KC_PROXY: "{{ .Values.configMap.kcProxy }}"
  KC_DB: "{{ .Values.configMap.kcDb }}"
  KC_DB_URL: "{{ .Values.configMap.kcDbUrl }}"
  KC_DB_URL_HOST: "{{ .Values.configMap.kcDbUrlHost }}"
  KC_DB_USERNAME: "{{ .Values.configMap.kcDbUsername }}"
  KC_DB_URL_PORT: "{{ .Values.configMap.kcDbUrlPort }}"
  KC_FEATURES: "{{ .Values.configMap.kcFeatures }}"